---
title: "CS_invasive"
output: html_document
date: "2024-06-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CS and invasive species overlap

Trying to figure out the overlap between our CS database and other databases of invasive species

First, read in files

```{r}
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyr)
library(cowplot)
library(wesanderson)


survey <- read.csv(file="978_species_clean_may17.csv"   , header=TRUE ) #Adjusted Nov 15 2023 to fix errors in duplicated species

# Load the WoRMS database (Not sure I need this???)
# This version, for whatever reason, is ONLY ANIMAL SPECIES (from Anne)
# That is fine; it's what I want anyway
worms <- read.csv('taxon.csv',header=TRUE) 

wrims<-read.csv(file="WRIMS_taxon.csv"   , header=TRUE )

#Now filter to only animal species
wrims<-filter(wrims,(kingdom=="Animalia" & taxonRank=="Species")) 
# 2716 species remaining


```
Next, take the species names, compare them, and put into a separate database

```{r}

overlap<- c() # blank dataframe

matchlist<-wrims$acceptedNameUsage %in% survey$acceptedName_wormsV1  #make vector of cases in wrims that have a match in the CS survey

#now this loop take the values for which there is a match and extracts them from the wrims set to make a dataframe
for (i in 1:length(matchlist)){
  if (matchlist[i] == TRUE)
    overlap<-rbind(overlap,wrims[i,])
}

write.csv(overlap,"invasive_CS.csv")

write.csv(table(overlap$class),"invasiveCS_class.csv")
write.csv(table(survey$class_wormsV1),"CS_class.csv")
write.csv(table(wrims$class),"invasive_class.csv")

```

Next step - heat map comparing the relative prevalence in the databases?

```{r}
overlapdata<-read.csv("C:/Users/aecsk/Documents/GitHub/Cryptic_species_figs/overlap_heatmap.csv",header=T)
overlaplarge<-read.csv("C:/Users/aecsk/Documents/GitHub/Cryptic_species_figs/heatmap_overlap_largeclasses.csv",header=T)

  ggplot(data = overlaplarge, mapping = aes(x = Dataset,
                                                 y = Class,
                                                 fill = zscore)) +
    geom_tile() +
    scale_fill_gradient2(low = 'blue', mid = 'white', high = 'red')+
    theme_bw()+
    theme(axis.title.x = element_blank(), 
          axis.title.y = element_blank(), 
          panel.background = element_blank(), 
          panel.grid.major = element_blank(),  
          panel.grid.minor = element_blank(),  
          plot.background = element_blank())
    #theme(legend.position="none") +
    #theme(axis.text.x=element_blank(),axis.text.y=element_blank())
    #facet_grid(~Dataset)

```

Let's check to see how many of the WRIMS species have ncbi data
```{r}
nomsp<-read.csv("DATASET_187603_NominalSpecies.csv",sep=";",header=TRUE)

ncbi_all<-filter(nomsp, ncbi == TRUE) # 38153 spp with NCBI data
  
matchlistncbi<-wrims$acceptedNameUsage %in% ncbi_all$acceptedNameUsage  #make vector of cases in wrims that have a match in the NCBI database
# this is 1610 out of 2716 total

wrimsncbi<-c()
#now this loop take the values for which there is a match and extracts them from the wrims set to make a dataframe
for (i in 1:length(matchlistncbi)){
  if (matchlistncbi[i] == TRUE)
    wrimsncbi<-rbind(wrimsncbi,wrims[i,])
}

overlapncbi<- c() # blank dataframe

matchlist4<-wrimsncbi$acceptedNameUsage %in% survey$acceptedName_wormsV1  #make vector of cases in wrims that have a match in the CS survey

#now this loop take the values for which there is a match and extracts them from the wrims set to make a dataframe
for (i in 1:length(matchlist4)){
  if (matchlist4[i] == TRUE)
    overlapncbi<-rbind(overlapncbi,wrimsncbi[i,])
}



```

```{r}
overlaptry<-read.table("overlaptry2.txt",header=TRUE)
ggplot(data = overlaptry, mapping = aes(x = proportionCS,
                                                 y = proportionWRIMS,
                                                 size = proportionoverlap))+
  geom_point()+
  geom_text(label=overlaptry$Class,nudge_y=0.005)+
  geom_abline(intercept = 0, slope = 1)+
  theme_bw()

ggplot(data = overlaptry, mapping = aes(x = proportionCS,
                                                 y = proportionoverlap))+
  geom_point()+
  geom_text(label=overlaptry$Class,nudge_y=0.005)+
  geom_abline(intercept = 0, slope = 1)+
  theme_bw()

ggplot(data = overlaptry, mapping = aes(x = proportionWRIMS,
                                                 y = proportionoverlap))+
  geom_point()+
  geom_text(label=overlaptry$Class,nudge_y=0.005)+
  geom_abline(intercept = 0, slope = 1)+
  theme_bw()

```

